DROP TABLE IF EXISTS routes;

CREATE TABLE routes (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  cca3 VARCHAR(250) NOT NULL,
  borders VARCHAR(500) NOT NULL,
  landlocked VARCHAR(250) DEFAULT NULL,
  latitutelongititute VARCHAR(250) DEFAULT NULL
);